package com.bbva.laboratorio.domain.models.enums;

public enum TipoMovimiento {
  DEPOSITO,
  EXTRACCION,
  TRANSFERENCIA_RECIBIDA,
  TRANSFERENCIA_REALIZADA,
  COMPRA_MONEDA_EXTRANJERA, DEPOSITO_EXTRACCION, COMPRA_VENTA_MONEDA_EXTRANJERA, VENTA_MONEDA_EXTRANJERA
}
